/F/I<,Fun,1001010001>,I(Fun"<0010100100100011>")M<I(IP,10010010101)>-=<Fun<,IP-=,<Fin.Fun=-2,100101010100=10-01>>>


/F/I<,Fun,1001010001>,I(Fun"<0010100100100011>")M<I(IP,10010010101)>-=<Fun<,IP-=,<Fin.Fun=-2,100101010100=10-01>>>:> 


/New/.co.co.co.co-=01000101001=.co.co.10-01.Fun/fun 

/New/.co.co.co.co-=01000101001=.co.co.010.L{<Fun<2>},010 -=2

/Co//"<Fun<New>,Fun<Co>/=2.co.co=010-1-0-1-0-1-0

/-Co-=2.<Fun>- /New/.co.co.co.co-=01000101001,<F,(Co,New)>)

Fun.Co.co-=2,01010100101010

,Co.L(<Fun.2\<F,(Co,New)>)

/Co,2\,<Fun,New>-010001001,2   




Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>
Co.co.Fun=2,L(F,<10-01>-1><-><2 Co.co.Fun=2,L(F,<1,1,01,10>-2><-><1 /Co.co.Fun,<F.<L,Co=2,010001=><Co,Fun<New>><>>

Fun,<,Co.Co-=,010,101,010001010,Fun.Co,Co=010001001-Fun,<L(010100010010><-><01000101001010)>>

/F,<<Fin<Min>"Fll<Dil:00100010\<Co.Co.(<<>F,<Fin,Fun,Min,Dun,Fl<FI<010010100010>>><>>)>>">

/F/T-=01010100:(Fin<,End>)

Co.Co.Con=Fin(Fin<,End>)















































